### ISSUE TITLE
Redirect does not work

### ISSUE THREAD

**Issue by guitar9** [adamkdean/redirect#10]
This is my docker-compose file

```
version: "3"

services:

  redirect:
    image: adamkdean/redirect:1.2.4
    networks:
      - proxy_net
    environment:
      - VIRTUAL_HOST=www.mydomain.de
      - REDIRECT_LOCATION=mydomain.de
      - REDIRECT_STATUS_CODE=301
      - PRESERVE_URL=true
  nginx:
    restart: always
    image: nginx:1.21.0
    container_name: mydomain
    volumes:
      - ./volume:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_net
    environment:
      - VIRTUAL_HOST=mydomain.de
      - LETSENCRYPT_HOST=mydomain.de
      - LETSENCRYPT_EMAIL=myemail@gmail.com

networks:
  proxy_net:
    external: true

```

When I call www.mydomain.de I get redirected to https://www.mydomain.de/%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://mydomain.de%22
